### ISSUE TITLE
Consider relationship between module linking and other bundling formats

### ISSUE THREAD

**Issue by littledan** [WebAssembly/module-linking#14]
It's great how module linking will enable several different WebAssembly modules, forming a module graph, to be distributed in another file. There are other efforts in the general area of bundling files together, e.g., [WebBundles](https://github.com/WICG/webpackage/). I've developed another framing of this, as "resource batches" ([gist](https://gist.github.com/littledan/e01801001c277b0be03b1ca54788505e), [slides](https://docs.google.com/presentation/d/1smfn5YiLCLgw30L4fbkaS-C3qxQdk3O4vt6E3DO7qxA/edit)). The big advantage of these more general types of bundling is that they can include multiple different types of assets together in one bundle.

I can see the value in the local simplicity for WebAssembly of this proposal--bundling fits naturally into other things that this proposal accomplishes, and bundling serves an important need. It may bring in excessive complexity to reference an external format defined outside of the WebAssembly CG; Web Bundles are not yet a standard, either. I don't think it's necessarily a bad thing if we end up having multiple bundling solutions in the WebAssembly ecosystem--one which bundles only Wasm, and another which bundles Wasm together with other asset types.

What are your thoughts on this overlap?

**Comment by lukewagner** [comment]
That's a great question; I've thought about this too.  I think the essential difference between Module Linking and bundling proposals is that the primary goal of Module Linking isn't optimization (of number of files/fetches/etc) but, rather, to expose a fundamentally new semantic operation to core wasm: being able to privately `instantiate` a module (rather than only being able to import shared, already-instantiated modules).  Moreover, while the proposal does allow modules to be nested, if you check out the [dynamic linking use case](https://github.com/WebAssembly/module-linking/blob/master/proposals/module-linking/Example-SharedEverythingDynamicLinking.md), what the toolchain naturally needs to do (in order to enable sharing of `libc` code) is to *import* the modules of shared libraries like `libc`.  Thus, in common linking scenarios, the choice of how to bundle modules will still be up to the final bundling tool.

**Comment by tysonrm** [comment]
You might be interested to see what we are doing with [module federation](https://module-federation.github.io/blog/get-started). A recent [article](https://trmidboe.medium.com/discounting-the-microservice-premium-a95311c61367?sk=0748ba059970b66a8b99c75b0f9cb4f3) on its application.

**Comment by lukewagner** [comment]
I think this issue is addressed, so I'll close it out, but feel free to reopen if there are additional questions/comments.
